<div style="text-align:center">
    <h1>
        VSL RL : SUMO Simulation
    </h1>
</div>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sys
sys.path.append('C:\PHD\Workspace\gym_sumo_vsl_maroc\gym_sumo\envs')
from utils import plot_policy, plot_action_values, test_agent
import SUMOInitializeEnv
import gym
import sumo_env as env
import ql_agent as QLAgent
import epsilon_greedy as EpsilonGreedy

/Users/asmae/opt/anaconda3/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(


Initialize the environment

In [2]:

from gym.envs.registration import register
from SUMOInitializeEnv import SUMOEnv_Initializer
register(
    id='SumoGUI-v0',
    entry_point='SUMOInitializeEnv:SUMOEnv_Initializer'
)
env = gym.make('SumoGUI-v0')

In [3]:
def create_uniform_grid(low,high, bins=(500,500)):
        grid= []
        for i, lower_upper in enumerate(zip(low,high)):
            grid_column= np.linspace(lower_upper[0], lower_upper[1], bins[i]+1)
            grid.append(grid_column)
        return grid

#### Q Learning

In [4]:
import traceback
action_space= np.array([19, 22, 25, 28, 31, 33])
try:
    for i in range(1):#episodes
        print(f"episode: {i}")
        initial_states = env.reset()
        #print(env.observation_space)
        action_space_size = len(env.action_space)
        state_grid= create_uniform_grid(env.observation_space.low, env.observation_space.high, bins= (400,400))
        ql_agents = QLAgent.QLAgent(starting_state=initial_states,
                                    state_space=env.observation_space,
                                    state_grid = state_grid,
                                    action_space=env.action_space,
                                    alpha=0.2,
                                    gamma=0.99,
                                    exploration_strategy=EpsilonGreedy.EpsilonGreedy())
        #print(f"action_space_size{action_space_size}")
        for t in range(1000):#time steps
            actions =ql_agents.act()
            print(f"act action : {actions}")
            s, r, done, _ = env.step(action=actions)
            print(f"current reward: {r}; current state: {s}")
            ql_agents.learn(next_state=s, reward=r)
            if done:
                break
        env.close()
except ValueError:
    print(traceback.format_exc())
    env.close()
        

episode: 0
 Retrying in 1 seconds


Fontconfig warning: ignoring UTF-8: not a valid region tag


maximizing action
[0. 0. 0. 0. 0. 0.]
Current action = 19, current state (3, 3)
act action : 19
reward: 9.110400871461584
current reward: 9.110400871461584; current state: [2.0, 0.0028441410693970416]
maximizing action
[0. 0. 0. 0. 0. 0.]
Current action = 19, current state (11, 3)
act action : 19
reward: 10.161682553371627
current reward: 10.161682553371627; current state: [2.0, 0.0028441410693970416]
maximizing action
[2.03233651 0.         0.         0.         0.         0.        ]
Current action = 19, current state (11, 3)
act action : 19
reward: 11.324628263615253
current reward: 11.324628263615253; current state: [2.0, 0.0028441410693970416]
maximizing action
[4.29726216 0.         0.         0.         0.         0.        ]
Current action = 19, current state (11, 3)
act action : 19
reward: 9.705181882198413
current reward: 9.705181882198413; current state: [3.0, 0.004266211604095562]
maximizing action
[0. 0. 0. 0. 0. 0.]
Current action = 19, current state (15, 3)
act action : 